default_language_version:
  python: python3

repos:
# Run the Ruff linter.
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.2
  hooks:
    # Run the Ruff linter.
    - id: ruff
    # Run the Ruff formatter.
    - id: ruff-format